
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - db.secyu.com
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.secyu.com
  resources:
  - redis/finalizers
  verbs:
  - update
- apiGroups:
  - db.secyu.com
  resources:
  - redis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - ""
    - apps
  resources:
    - pods
    - secrets
    - statefulsets
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
